; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 115200

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-110

